
#tomcat server
server:
  port: 8080


#jpa

  spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

#datasource
    datasource:
      url: jdbc:mysql://localhost:3306/ciceT612?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root



